USE DIVYA;
CREATE TABLE SATE_BANK_OF_INDIA
(
EMP_NO INT,
ENAME VARCHAR(20),
JOB VARCHAR(10),
MRG INT,
HIREDATRE DATE,
SAL INT,
COMM INT,
DEP_NO INT);
ALTER TABLE SATE_BANK_OF_INDIA MODIFY COLUMN HIREDATRE as HIREDATE
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7369, "SMITH", "CLERK", 7902, CAST("1980-01-12" AS DATE), 800, NULL, 20);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7499, "ALLEN", "SALESMAN", 7698, CAST("1981-02-20" AS DATE), 1600, 300, 30);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7521, "WARD", "SALESMAN", 7698, CAST("1981-02-22" AS DATE), 1250, 500, 30);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7566, "JONES", "MANAGER", 7839, CAST("1981-04-02" AS DATE), 2975, NULL, 20);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7654, "MARTIN", "SALESMAN", 7698, CAST("1981-09-28" AS DATE), 1250, 1400, 30);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7698, "BLAKE", "MANAGER", 7839, CAST("1981-05-01" AS DATE), 2850, NULL, 30);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7782, "CLARK", "MANAGER", 7839, CAST("1981-06-09" AS DATE), 2450, NULL, 10);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7654, "SCOTT", "ANALYST", 7566, CAST("1982-12-03" AS DATE), 3000, NULL, 20);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7839, "KING", "PRESIDENT", NULL, CAST("1981-11-17" AS DATE), 5000, NULL, 10);
INSERT INTO SATE_BANK_OF_INDIA VALUE
(7844, "TURNER", "SALESMAN", 7698, CAST("1981-09-08" AS DATE), 1500, NULL, 30);
SELECT * FROM SATE_BANK_OF_INDIA;

USE DIVYA;
CREATE TABLE DEPT
(
DEPT_NO INT,
DEPT_NAME VARCHAR(20),
LOC VARCHAR(20)
);
INSERT INTO DEPT VALUES
(10, "ACCOUNTING", "NEWYORK");
INSERT INTO DEPT VALUES
(20, "RESEARCH", "DALLAS");
INSERT INTO DEPT VALUES
(30, "SALES", "CHICAGO");
INSERT INTO DEPT VALUES
(40, "OPERATIONS", "BOSTON");
SELECT * FROM DEPT;






DESC STATE_BANK_OF_INDIA;
DESC DEPT;


SELECT 
      E.EMP_NO, E.ENAME, E.JOB,D.DEPT_NAME
FROM  
      SATE_BANK_OF_INDIA
INNER JOIN 
         DEPT D
ON E.DEP_NO = D.DEPT_NO;
         
      
SELECT 
      E.MRG, E.HIREDATRE, E.SAL, E.COMM, D.LOC
FROM  
      SATE_BANK_OF_INDIA E
INNER JOIN 
         DEPT D
ON E.DEP_NO = D.DEPT_NO;

SELECT 
      E.EMP_NO, E.ENAME, SAL, D.LOC
FROM
      SATE_BANK_OF_INDIA E
LEFT JOIN 
         DEPT D
 ON E.EMP_NO = D.DEPT_NO;       
 
 SELECT
       E.HIREDATRE, E.JOB, E.COMM, E.EMP_NO
FROM
       SATE_BANK_OF_INDIA E
 RIGHT JOIN
           DEPT D
 ON E.EMP_NO = D.DEPT_NO;     
 
 
SELECT
      E.SAL, E.DEP_NO, E.COMM, E.MRG
FROM
     SATE_BANK_OF_INDIA E
FULL OUTER JOIN
         DEPT D
ON E.EMP_NO = D.DEPT_NO;    

     
      
         














